#!/usr/bin/env bash
menu_launch() {
	fuzzel \
		--hide-before-typing \
		--lines 1 \
		--minimal-lines \
		--width 20 \
		--anchor bottom \
		--y-margin 50
}
pgrep -x fuzzel && {
	killall -e fuzzel
	exit 0
}
menu_launch
