#!/usr/bin/env bash
data_file="$HOME/.config/lutris_gamelist.json"
set -euo pipefail
pgrep -x fuzzel && {
    killall -e fuzzel
    exit 0
}
generate_data_file() {
    lutris --list-games --json > "$data_file"
}
[[ ! -f "$data_file" ]] && generate_data_file
[[ "${@:-}" == "--refresh" ]] && {
	rm "$data_file"
	generate_data_file
	notify-send "Lutris wrapper database has been updated!"
	exit
}
[[ "${@:-}" == "--gamescope" ]] && {
	arg="--mesg"
	mesg="gamescope=on"
	microcompositor=1
}
chosen_game=$(
	jq -r '.[].name' "$data_file" |
    fuzzel \
		"${arg:-}" "${mesg:-}" \
		--mesg-mode expand \
		--hide-prompt \
        --dmenu \
		--minimal-lines \
		--lines 30 \
		--width 54
) 
[[ -z "$chosen_game" ]] && exit 1
game_id=$(
	jq \
		-r \
		--arg n "$chosen_game" \
		'.[] | select(.name == $n) | .id' \
		"$data_file"
)
[[ -n "$game_id" ]] && lutris lutris:rungameid/"$game_id"
