#!/usr/bin/env bash
pgrep -x fuzzel && {
	killall -e fuzzel
	exit 0
}
file_chosed=$(
fuzzel \
	--dmenu \
	--width 13 \
	--hide-prompt \
<<EOF
󱢣 General
 Keybinds
 Startup
󱃻 Variables
󱂬 WindowRules
󱢣 Animations
EOF
)
case "$( echo "$file_chosed" | awk '{print $2}' )" in
    General)
		conf_file="$HOME/.config/mango/config.conf"
		;;
    Keybinds)
		conf_file="$HOME/.config/mango/keybinds.conf"
		;;
    Startup)
		conf_file="$HOME/.config/mango/startup.conf"
		;;
    Variables)
		conf_file="$HOME/.config/mango/variables.conf"
		;;
    WindowRules)
		conf_file="$HOME/.config/mango/windowrules.conf"
		;;
    Animations)
		conf_file="$HOME/.config/mango/animations.conf"
		;;
esac
[[ -n "$file_chosed" ]] && footclient bash -c "nvim $conf_file"
