#!/usr/bin/env bash
set -euo pipefail
pid_file="$XDG_RUNTIME_DIR/openvpn.pid"
path_to_files="$HOME/misc/openvpn_files/"
init() {
    vpn_file="$(find "$path_to_files" \
            -maxdepth 1 \
            -type f \
            -printf '%f\n' | sort | sed 's/.ovpn//g'|
        rofi -dmenu \
            -no-fixed-num-lines \
            -theme vpn_menu)"
    [[ -z "$vpn_file" ]] && exit 0
    pkexec \
		openvpn \
        	--config ${path_to_files}${vpn_file}.ovpn \
        	--daemon \
        	--writepid "$pid_file"
    notify-send "OpenVPN connection “${vpn_file}” is up and running!"
}
terminate() {
	pkexec kill "$(cat $pid_file)"
	rm -f "$pid_file"
}
dialog() {
dialog=$(
fuzzel \
	--dmenu \
	--width 15 \
	--hide-prompt \
<<EOF | awk '{print $1}'
Change server
Kill connection
EOF
)
}
if [[ ! -f "$pid_file" ]]; then
    init
else
    dialog
	case "$dialog" in
		Change)
			terminate
			init
			;;
		Kill)	
			terminate
			notify-send "OpenVPN process has been terminated!"
			;;
	esac
fi
