#!/usr/bin/env bash
launch_menu() {
chosen_script=$(
fuzzel \
	--dmenu \
	--hide-prompt \
	--width 14 \
<<EOF
wleave
mpv_fzf
sync_media
sync_wlpr
font_list
openvpn_init
wallpaper_fzf
check_storage
EOF
)
"$chosen_script"
}
pgrep -x fuzzel && {
	killall -e fuzzel
	exit 0
}
launch_menu
