#!/bin/bash
pgrep -x swayidle && {
    notify-send "There is a swayidle session running!"
    exit 1
}
swayidle -w \
    timeout 290 'dim -a 0.8' \
    timeout 300 'wlr-randr --output VGA-1 --off' \
    resume 'wlr-randr --output VGA-1 --on' \
