#!/usr/bin/env bash
set -m
output_directory=$HOME/.temp_streaming
[[ ! -d "$output_directory" ]] && mkdir "$output_directory"
whatsitgonnabe=$(
	echo -e "Sync\nClean" |
	fuzzel \
		--hide-prompt \
		--width 6 \
		--dmenu
)
case "$whatsitgonnabe" in
	Sync)
		URL="$(wl-paste)"
		[[ ! "$URL" =~ ^(https[://].*|http[://].*)$ ]] && {
			notify-send "No media URL has been provided!"
			exit 1
		}
		[[ -n "$(pgrep -x aria2c)" ]] && {
			notify-send "Aria2c is downloading something already"
			exit 0
		}
		footclient bash -c "aria2c -d $output_directory $URL; read" & disown
		;;
	Clean)
		rm ${output_directory}/*
		exit 0
		;;
	*)
		;;
esac
