#!/usr/bin/env bash
wlpr_dir="$HOME/wlpr_imgs"
page="1"
wlpr_url=$(
	curl -s \
	"https://wallhaven.cc/api/v1/search?ratios=16x9,16x10&categories=100&purity=100&sorting=toplist&page=$page" |
	jq -r '.data.[] | .path' |
	fzf \
		--no-input \
		--style=full \
		--reverse \
		--cycle \
		--preview="
			curl -s {} |
			magick - \
				-thumbnail x688 \
				-gravity center \
				-crop 620x688+0+0 - |
			chafa
		"
)
cd "$wlpr_dir" && curl -s -O "$wlpr_url"
