#!/bin/bash

export XDG_CURRENT_DESKTOP=wlroots
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=wlroots
export QT_QPA_PLATFORMTHEME=qt6ct
export XCURSOR_THEME=Simp1e-Tokyo-Night

dbus-run-session dwl -s dwl_startup
