#!/bin/bash

if pgrep -x rofi; then
	killall rofi
else
	cliphist list |
        rofi -dmenu -no-fixed-num-lines -theme \
            ~/.config/rofi/clipboard_history.rasi |
        cliphist decode |
        wl-copy
fi
