#!/bin/bash

file="/home/fenrjon/screen_dumps/recordings/$(date +%s%N)_screencast.mp4"

if pgrep -x wl-screenrec > /dev/null; then
	killall wl-screenrec
	exit
else
	wl-screenrec --audio --audio-device alsa_output.pci-0000_00_1f.3.hdmi-stereo.monitor --filename "$file" --no-cursor
fi

if [ -f "$file" ]; then
	notify-send -i video "Screen recording finished!" "$file"
fi


