#!/bin/bash

file="/home/fenrjon/screen_dumps/$(date +%s_%d_%m_%Y_)screenshot.png"

capture_section() {
	wayshot -s "$(slurp)" -f "$file"
}

capture_output() {
	wayshot -f "$file"
}

copy_clipboard() {
	wl-copy --type image/png < "$file"
}

case "$1" in
	--section)
	capture_section && copy_clipboard ;;
	--output)
	capture_output && copy_clipboard ;;
	--help|"")
	echo "Usage: $0 [--section | --output | --help]" ;;
	*)
	echo "Unknown option: $1"
	exit 1 ;;
esac

notify-send -i $file "Screen dumped sucessfuly" "$file" 
