#!/bin/bash

tmrval=$1
start=$(date +%s)

if [[ "$DETACHED" != "1" ]]; then
    export DETACHED=1
    setsid "$0" "$@" > /dev/null 2>&1 &
    exit 0
fi

case "$tmrval" in
	*s) duration=${tmrval%s} ;;
	*m) duration=$(( ${tmrval%m} * 60 )) ;;
	*h) duration=$(( ${tmrval%h} * 3600 )) ;;
	*) duration=${tmrval%s} ;;
esac

while true; do
	now=$(date +%s)
	elapsed=$((now - start))
	sleep 0.05
	if (( elapsed >= duration )); then
		notify-send -i clock "Timer" "Time is up!"
		break
	fi
done

