#!/bin/bash

day=$(date +%d)
month=$(date +%B)
year=$(date +%Y)
weekday=$(date +%A)

day_num=$(echo "$day" | sed 's/^0//')

case $day_num in
	1|21|31) suffix="st" ;;
	2|22) suffix="nd" ;;
	3|23) suffix="rd" ;;
	*) suffix="th" ;;
esac

echo "󰭧 ${day_num}${suffix} ${month} of ${year}, ${weekday}"
