#!/bin/bash
stt=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |
    awk '/state/ {print $2}')
bt_int=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |
    awk '/percentage/ {gsub(/%/, ""); print $2}')
bt_pg=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |
    awk '/percentage/ {print $2}')
if [[ "$stt" == "discharging" ]]; then
	if [[ "$bt_int" -eq 100 && "$bt_int" -ge 95 ]]; then
		echo " Fully charged"
	elif [[ "$bt_int" -ge 70 ]]; then
		echo " $bt_pg $stt"
	elif [[ "$bt_int" -ge 50 ]]; then
		echo " $bt_pg $stt"
	elif [[ "$bt_int" -ge 35 ]]; then
		echo " $bt_pg $stt"
	elif [[ "$bt_int" -le 10 ]]; then
		echo "󰀦 CRITICAL:  $bt_pg $stt"
	fi
elif [[ "$stt" == "charging" ]]; then
	icons=(    )
	echo "${icons[$(( $(date +%s) % 5 ))]} $bt_pg $stt"
elif [[ "$stt" == "fully-charged" ]]; then
	echo " Fully charged"
fi
