#!/bin/bash
file="$HOME/screen_dumps/$(date +%s%n).png"
if [[ -z "$1" ]]; then
	scrot -F $file -e 'xclip -selection clipboard -t image/png -i $f'
elif [[ "$1" == "--select" ]]; then
	scrot -s -F $file -e 'xclip -selection clipboard -t image/png -i $f'
fi
if [[ -f "$file" ]]; then
    notify-send -i $file "Screen dumped!" "$file"
else
    notify-send "Couldn't dump screen, an error has occurred!"
fi
