#!/bin/bash

if [[ "$1" == "rm" || "$1" == "add" || "$1" == "info" ]] && [[ -z "$2" ]]; then
    echo -e "No package name passed\nAborting"
    exit
fi

case "$1" in
    ls) pacman -Qsq | fzf --layout=reverse | wl-copy;;
    rm) sudo pacman -Rns "$2";;
    add) sudo pacman -S "$2";;
    info) pacman -Si "$2";;
    *) echo -e "ls     Display list\nrm     Uninstall package\nadd    Install package";;
esac
