#!/bin/bash
preset_list=$(easyeffects -p |
	awk '
		/^Output/ { in_output=1; next }
		/^[[:space:]]*Input/ { in_output=0 }
		in_output && NF {
			sub(/^[[:space:]]*[0-9]+[[:space:]]+/, "")
			if ($0 !~ /^No/ && NF)
				print
		}
	' \
	| sort )
chosen_preset=$(printf '%s\n' "$preset_list" |
	rofi \
        -dmenu \
        -no-fixed-num-lines \
        -theme easyeffects_profile_menu)
[[ -z "$chosen_preset" ]] && exit 1
[[ "$(easyeffects -a output)" == "$chosen_preset" ]] && {
    notify-send "The preset you've just selected is already set!"
    exit 0
}
if easyeffects -l "$chosen_preset"; then
    notify-send "Sound profile “${chosen_preset}” has been set successfully!"
else
    notify-send "Could not set profile “${chosen_preset}”, an error has occurred!"
fi
