#!/bin/bash
data_file="$HOME/.config/lutris_gamelist.json"
screen_width="1440"
screen_height="900"
if pgrep -x rofi; then
    killall -e rofi
    exit 0
elif pgrep -x gamescope-wl; then
    notify-send "There is another gamescope session running!"
    exit 0
fi
generate_data_file() {
    lutris --list-games --json > "$data_file"
}
[[ ! -f "$data_file" ]] && generate_data_file
[[ "$1" == "refresh" ]] && {
    rm "$data_file"
    generate_data_file
}
chosen_game=$(jq -r '.[] .name' "$data_file" |
    rofi \
        -dmenu \
        -theme game_launcher \
        -no-fixed-num-lines) 
game_id=$(jq '.[] | { ( .name ): { id: .id } }' "$data_file" |
    jq -s add |
    jq --arg var "$chosen_game" '.[$var].id')
case "$game_id" in
    17)
        screen_width="1152"
        screen_height="720"
    ;;
    36|37|35|19|5)
        screen_width="1280"
        screen_height="800"
    ;;
    *);;
esac
[[ -z "$chosen_game" ]] && exit 1
gamescope \
    --expose-wayland \
    --force-windows-fullscreen \
    --force-grab-cursor \
    --fullscreen \
    -w "$screen_width" -h "$screen_height" -r 60 \
    -- lutris lutris:rungameid/"$game_id"
