#!/bin/bash

export mesa_glthread=true
export vblank_mode=0

data_file="/home/fenrjon/.config/lutris_gamelist.json"
rofi_theme="~/.config/rofi/game_launcher.rasi"

n_w="1440"
n_h="900"

if pgrep -x rofi; then
    killall -e rofi
    exit
fi

gen_df() {
    lutris --list-games --json > "$data_file"
}

if [ ! -f "$data_file" ]; then
    gen_df
elif [ "$1" == "refresh" ]; then
    rm "$data_file"
    gen_df
fi

game_list=$(jq '.[] | { ( .name ): { id: .id } }' "$data_file" |
    jq -s add)

chosen_game=$(jq -r '.[] .name' "$data_file" |
    rofi \
        -dmenu \
        -theme "$rofi_theme" \
        -no-fixed-num-lines)

game_id=$(echo "$game_list" |
    jq --arg var "$chosen_game" '.[$var].id')

case "$game_id" in
    17)
        n_w="1152"
        n_h="720"
    ;;
    36|37|35|19|5)
        n_w="1280"
        n_h="800"
    ;;
    *);;
esac

if [ -z "$chosen_game" ]; then
    echo "Select a game to launch with Gamescope"
    exit 0
else
    gamescope \
        --force-windows-fullscreen \
        --force-grab-cursor \
        --fullscreen \
        -w "$n_w" -h "$n_h" -r 60 \
        -- lutris lutris:rungameid/"$game_id"
fi
