#!/bin/bash
cd "$HOME/wlpr_imgs/"
wallpaper=$(for a in *.*;
do
	echo -en "$a\0icon\x1f$a\n";
done \
| rofi \
	-dmenu \
	-no-fixed-num-lines \
	-theme wallpaper_set )
[[ -z "$wallpaper" ]] && exit 1
swww img "$wallpaper" &
wallust run "$wallpaper" & 
exit 0
