#!/bin/bash

export mesa_glthread=true
export vblank_mode=0

game_list="30 Age of Empires III: Complete Collection
5 Assassin's Creed Brotherhood
19 Assassin's Creed II
35 Assassin's Creed Revelations
3 Dark Souls: Prepare to Die Edition
37 Dead Space
4 Fable: The Lost Chapters
36 Gears of War
9 Minecraft
2 Star Wars: Knights of the Old Republic
7 Star Wars: Knights of the Old Republic II - The Sith Lords
38 Super Mario Bros. 3
17 The Elder Scrolls V: Skyrim
23 The Legend of Zelda: Majora's Mask 
27 The Legend of Zelda: Ocarina of Time"

game_id=$(echo "$game_list" |
    fzf --no-input \
        --layout=reverse \
        --with-nth 2.. |
    awk '{print $1}')

case "$game_id" in
    17)
        n_w="1152"
        n_h="720"
    ;;
    36|37|35|19|5)
        n_w="1280"
        n_h="800"
    ;;
    *)
        n_w="1440"
        n_h="900"
    ;;
esac

if [ -z "$game_id" ]; then
    echo "Select a game to launch with Gamescope"
else
    gamescope \
        --force-windows-fullscreen \
        --force-grab-cursor \
        -f -r 60 \
        -W 1440 -H 900 \
        -w "$n_w" -h "$n_h" \
        -- lutris lutris:rungameid/$game_id
fi
