#!/usr/bin/env bash
list_file="$HOME/.config/eassyeffects_presets.json"
active_preset_file="$HOME/.config/eassyeffects_active_preset"
pgrep -x fuzzel && {
	killall -e fuzzel
	exit
}
generate_list_file() {
	easyeffects -p |
	awk '
		/^Output/ { in_output=1; next }
		/^[[:space:]]*Input/ { in_output=0 }
		in_output && NF {
			sub(/^[[:space:]]*[0-9]+[[:space:]]+/, "")
			if ($0 !~ /^No/ && NF)
				print
		}
	' |
	sort | jq -nR '[inputs]' > $list_file
}
generate_active_preset_file() {
	easyeffects -a output > "$active_preset_file"
}
[[ ! -f "$list_file" ]] && generate_list_file
[[ ! -f "$active_preset_file" || -z $(cat "$active_preset_file") ]] && {
	generate_active_preset_file
}
[[ "$@" == "--refresh" ]] && {
	generate_active_preset_file
	generate_list_file
	exit 0
}
active_preset=$(cat "$active_preset_file")
chosen_preset=$(
	jq -r '.[]' $list_file |
	sed "/$active_preset/s/^/󰺢 /" |
	fuzzel \
		--dmenu \
		--width 25 \
		--hide-prompt |
	sed "s/󰺢 //g"
)
[[ -z "$chosen_preset" ]] && exit 1
[[ "$active_preset" == "$chosen_preset" ]] && {
    notify-send "The preset you've just selected is already set!"
    exit 0
}
easyeffects -l "$chosen_preset" && {
	echo "$chosen_preset" > "$active_preset_file"
	notify-send "Sound profile “${chosen_preset}” has been set successfully!"
	exit 0
}
notify-send "Could not set profile “${chosen_preset}”, an error has occurred!"
