#!/usr/bin/env bash
set -euo pipefail
[[ -z "$(file -i  "$HOME"/.temp_streaming/* | grep 'video/')" ]] && {
	notify-send "Media folder is empty!"
	exit 0
}
[[ -n "$(pgrep -x mpv)" ]] && {
	notify-send "MPV is already running!"
	exit 0
}
footclient -a mpv_fzf_scratchpad bash -c '
	while true
	do
		set -m
		find "$HOME"/.temp_streaming/* \
			-type f \
			! -iregex ".*aria2.*" | sort | 
		fzf \
			--bind "enter:execute:nohup mpv --no-terminal {} >/dev/null 2>&1 & disown" \
			--reverse \
			--cycle \
			--no-input \
			--style=full \
			--wrap=word \
			--wrap-sign= \
			--delimiter / --with-nth -1 \
			--preview-window='right:40%:wrap' \
			--preview="
				ffmpeg \
					-i {} \
					-ss 00:00:28 \
					-vf "thumbnail" \
					-vf scale=490:-1 \
					-frames:v 1 \
					-f image2pipe pipe:1 \
					-loglevel quiet |
				chafa
				"
	done
'
