#!/usr/bin/env bash
file="$HOME/screen_dumps/recordings/$(date +%s%N).mp4"
pgrep -x wl-screenrec && {
	killall wl-screenrec
	exit 0
}
if wl-screenrec \
	"$@" \
	--audio \
	-b "3 MB" \
	--audio-device alsa_output.pci-0000_00_1f.3.hdmi-stereo.monitor \
    --filename "$file"; then
notify-send -i video "Screen recording finished!" "$file"; else
notify-send -i video "Screen recording failed!"
fi
