#!/usr/bin/env bash
#---------------------------------------------------------------------#
dir="$HOME/screencasts/"; file="${dir}$(date +%s%N).mp4"
icon="camera-video"; appname="Screencast Manager"
audio_card='alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
#------------------------------------------------------------------#
msgs=("File: "$file"" "The file could not be found at the screenshots directory")
#-------------------------------------------------------------#
pkill -x wl-screenrec && exit 0; mkdir -p "$dir"; wl-screenrec \
	--audio --audio-device "$audio_card" \
	--bitrate "3 MB" -f "$file" && { [[ -f "$file" ]]; } && {
	notify-send -a "$appname" -i "$icon" "Screencast file has been saved" "${msgs[0]}"; exit 0
};	notify-send -a "$appname" -i "$icon" "Screencast file hasn't been saved" "${msgs[1]}"; exit 1
#--------------------------------------------------------------------------------------------------#
