#!/bin/bash
file="$HOME/screen_dumps/recordings/$(date +%s%N).mp4"
pgrep -x wl-screenrec && {
	killall wl-screenrec
	exit 0
}
wl-screenrec --audio --audio-device alsa_output.pci-0000_00_1f.3.hdmi-stereo.monitor \
    --filename "$file" \
[[ -f "$file" ]] && notify-send -i video "Screen recording finished!" "$file"
