#!/bin/bash

file="/home/fenrjon/screen_dumps/$(date +%s%N_)screenshot.png"

copy() {
	wl-copy --type image/png < "$file"
}

case "$1" in
	-s)
	wayshot -s "$(slurp)" -f "$file" && copy ;;
	-o)
	wayshot -f "$file" && copy ;;
	*)
	echo "idk what that is"
	exit 1 ;;
esac

if [ -f "$file" ]; then
	notify-send -i $file "Screen dumped sucessfuly" "$file"
fi
