#!/usr/bin/env bash
set -m
footclient -a wallpaper_fzf_scratchpad bash -c '
	rg "$HOME/wlpr_imgs" \
		-g "*.{png,jpg}" \
		--files \
		--sortr created |
	fzf \
		--no-input \
		--cycle \
		--delimiter / \
		--reverse \
		--style=full \
		--with-nth -1 \
		--wrap \
		--wrap-sign= \
		--bind "enter:execute:
			nohup wallust run {} >/dev/null 2>&1 & disown
			nohup awww img {} >/dev/null 2>&1 & disown
		" \
		--preview="
			magick {} \
				-quiet \
				-thumbnail 450x \
				-gravity center \
				-crop 450x260+0+0 - | \
			chafa
		"
'
